---
- name: Deploy NGINX server
  hosts: all
  become: yes

  tasks:
    - name: Ensure NGINX is installed
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Ensure NGINX is running and enabled
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Open port 80 for HTTP
      ufw:
        rule: allow
        port: '80'
        proto: tcp

